# Generated by Django 4.1 on 2022-09-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingmail',
            name='date_enter',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='incomingmail',
            name='id_enter',
            field=models.CharField(default='aaa', max_length=200),
            preserve_default=False,
        ),
    ]
