# Generated by Django 4.1 on 2022-09-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_incomingmail_date_enter_incomingmail_id_enter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingmail',
            name='regarding',
            field=models.TextField(),
        ),
    ]
