# Generated by Django 4.1 on 2022-09-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_alter_incomingmail_regarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingmail',
            name='file_or_image',
            field=models.FileField(blank=True, null=True, upload_to='storage/incoming-mail/'),
        ),
        migrations.AlterField(
            model_name='outgoingmail',
            name='file_or_image',
            field=models.FileField(blank=True, null=True, upload_to='storage/outgoing-mail/'),
        ),
    ]
